### PR TITLE
Refactor caches

### PR DESCRIPTION
**Pull request by nicolasvasilache**
This PR is the first step towards a CpuTcExecutor with caching.
It refactors and simplifies the cache API.
The TcExecutor interaction with caches will be simpler after this is landed.
This is stacked on top of other PRs, so only review starting 292d380 please.

### CODE REVIEW

**Comment by ttheodor** [comment]
@caffe2bot retest this please

**Comment by nicolasvasilache** [comment]
@caffe2bot retest this please

**Comment by nicolasvasilache** [comment]
@caffe2bot retest

**Comment by nicolasvasilache** [comment]
@caffe2bot retest this please

**Comment by nicolasvasilache** [comment]
@caffe2bot retest this

**Comment by nicolasvasilache** [comment]
@caffe2bot retest this please

**Comment by ttheodor** [comment]
CI mitigation test signoff: @ttheodor

**Comment by ftynse** [comment]
Note that this PR is still **stacked**

**Comment by ftynse** [comment]
Tests pass locally / @ftynse

**NOTE:** I have not reviewed this PR yet, just ran the tests.  It is stacked on top of #235 and #228 and those should be reviewed/merged first unless this PR is rebased on top of master instead.

**Comment by nicolasvasilache** [comment]
Yes all will be rebased before landing as appropriate. 
There is a glimmer of hope here with CI so trying to let this one go through.

**Pull request merged**
