### PR TITLE
outputRanges: use isl::map::get_range_simple_fixed_box_hull

### PR DESCRIPTION
**Pull request by skimo-openhub**
The computation is fairly low-level.  Let isl take care of it.
TensorReferenceGroup::promotion no longer needs to fiddle
with the output space because the space is preserved
by isl::map::get_range_simple_fixed_box_hull.

### CODE REVIEW

**Comment by ftynse** [comment]
Let me see how this combines with #472 first, there are other space-related modifications.

**Comment by skimo-openhub** [comment]
On Tue, Jun 05, 2018 at 01:33:18AM -0700, ftynse wrote:
> Let me see how this combines with #472 first, there are other space-related modifications.

Well... one of the main goals of these changes was to make it easier
for you to do #472, but you apparently decided not to use them...

skimo

**Comment by ftynse** [comment]
Well, I prefer to do things rather than to wait until something else gets done before I can even start thinking about what I want.  We already work 3 times slower than we used to.  Otherwise I can just stop coding.

**Comment by skimo-openhub** [comment]
On Tue, Jun 05, 2018 at 02:17:40AM -0700, ftynse wrote:
> Well, I prefer to do things rather than to wait until something else gets done before I can even start thinking about what I want.  We already work 3 times slower than we used to.  Otherwise I can just stop coding.

AFAIK, you worked on your changes last week, while I made the extent
changes available to you (in test/extent) at the end of the week before.
All that changed since then is the commit id of the isl submodule.

skimo

**Pull request merged**
