### PR TITLE
Add ccache stats during build time

### PR DESCRIPTION
**Pull request by prigoyal**
these stats logging should tell something about the ccache getting hit or not during build time.

### CODE REVIEW

**Comment by ftynse** [comment]
yes please! but needs fixes to the script

**Comment by prigoyal** [comment]
thank you @ftynse , I have added the missing function to the script. :)

**Comment by ftynse** [comment]
thanks, let's see what is printed on the CI machines

**Comment by prigoyal** [comment]
Hi @ftynse , I looked at the console output of all the builds on this PR and the cache hit is > 99.66% 

May I kindly request for your review again? :) thanks

**Pull request merged**
