### PR TITLE
[wip] Add cpp test for autotuner intermittent error as per request

### PR DESCRIPTION
**Pull request by prigoyal**
adding a C++ test as requested in https://github.com/facebookresearch/TensorComprehensions/issues/207

I tried to repro the error by using various mapping options pasted by user but couldn't repro it. But here is the playground for people to debug this further.

### CODE REVIEW

**Comment by ftynse** [comment]
I can't reproduce it either.

Here's the code for the supposedly offending options, in case somebody wants to stare at it and find an error.

```
__global__ void function_grad_9_656_32_92_32_32(int32 A, int32 C, int32 H, int32 L, int32 N, int32 W, float32* pI_grad, float32* pS_grad, int32* pR_grad, int32* pR2_grad, const float32* pI, const float32* pS, co
nst int32* pR, const int32* pR2, const float32* poutput_grad) {
  int b0 = blockIdx.x; int b1 = blockIdx.y; int b2 = blockIdx.z;
  int t0 = threadIdx.x; int t1 = threadIdx.y; int t2 = threadIdx.z;
  float32 (*I_grad)[656][32][32] = reinterpret_cast<float32 (*)[656][32][32]>(pI_grad);
  float32 (*S_grad) = reinterpret_cast<float32 (*)>(pS_grad);
  int32 (*R_grad)[9] = reinterpret_cast<int32 (*)[9]>(pR_grad);
  int32 (*R2_grad) = reinterpret_cast<int32 (*)>(pR2_grad);
  const float32 (*I)[656][32][32] = reinterpret_cast<const float32 (*)[656][32][32]>(pI);
  const float32 (*S) = reinterpret_cast<const float32 (*)>(pS);
  const int32 (*R)[9] = reinterpret_cast<const int32 (*)[9]>(pR);
  const int32 (*R2) = reinterpret_cast<const int32 (*)>(pR2);
  const float32 (*output_grad)[92][32][32] = reinterpret_cast<const float32 (*)[92][32][32]>(poutput_grad);
  S_grad[t0] = 0.000000f;
  S_grad[(t0 + 164)] = 0.000000f;
  S_grad[(t0 + 328)] = 0.000000f;
  S_grad[(t0 + 492)] = 0.000000f;
  __syncthreads();
  if (t0 <= 31) {
    for (int c0 = 0; c0 <= 31; c0 += 1) {
      for (int c1 = 0; c1 <= 655; c1 += 1) {
        for (int c2 = 0; c2 <= 31; c2 += 1) {
          I_grad[c0][c1][c2][t0] = (S[c1]*output_grad[c0][R2[c1]][c2][t0]);
        }
      }
    }
  }
  __syncthreads();
  R2_grad[t0] = 0;
  R2_grad[(t0 + 164)] = 0;
  R2_grad[(t0 + 328)] = 0;
  R2_grad[(t0 + 492)] = 0;
  __syncthreads();
  if (t0 <= 8) {
    for (int c0 = 0; c0 <= 91; c0 += 1) {
      R_grad[c0][t0] = 0;
    }
  }
  __syncthreads();
  for (int c0 = t0; c0 <= 655; c0 += 164) {
    for (int c1 = 0; c1 <= 31; c1 += 1) {
      for (int c2 = 0; c2 <= 31; c2 += 1) {
        for (int c3 = 0; c3 <= 31; c3 += 1) {
          S_grad[c0] = (S_grad[c0] + (I[c1][c0][c2][c3]*output_grad[c1][R2[c0]][c2][c3]));
        }
      }
    }
  }
}
```

**Comment by prigoyal** [comment]
@caffe2bot retest this please

**Comment by prigoyal** [comment]
@caffe2bot retest this please

**Comment by prigoyal** [comment]
@caffe2bot retest this please

**Comment by prigoyal** [comment]
@ftynse , @skimo-openhub , should this PR be merged or closed?

**Comment by prigoyal** [comment]
@ftynse should this PR be closed or merged?

**Comment by ftynse** [comment]
The error was not reproduced, so let's close it

**Pull request closed without merging**
