### PR TITLE
Suppress warnings

### LINKED ISSUE #456: Add a flag to supress warnings
Currently, TC will emit warnings about preconditions not being checked and non-initialized reductions.  When developing TC kernels, these are useful.  But when autotuning, these are only annoying as they appear in each compilation.  Add a `-w` flag that suppresses warning output.

### PR DESCRIPTION
**Pull request by ftynse**
Currently, warnings are always emitted during TC parsing (including
bounds inference) and semantic analysis.  This leads to megabytes of
identical warning spew in the autotuning, among other problems.
Introduce a boolean flag, "--warn", to control whether warnings should
be printed.  Set it to true by default.

This required to introduce the gflags support into the tc_lang library:
previously, flags were concentrated in the tc_core library, but tc_core
links to tc_lang making it impossible to put lang-specific flags in
core.  As a consequence, tc_lang now links gflags statically and
tc_core does not.  This is not a problem since tc_core links tc_lang
anyway.

Introducing even more gflags is not the best solution, since they are essentially global variables, but it is a pragmatic one.  We want to consider introducing some `CompilerOptions` structure that would include `MappingOptions` and other configurations (for example, kernel timeout), but I expect the discussion to take long.

Closes #456

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
Looks good, not immediately clear to me why the linking error pops up though

**Comment by ftynse** [comment]
Neither is it to me.  There is no linking problem on my local machine.  I also don't see any dynamic linking of gflags.  It is true that `tc_core` links `tc_lang` dynamically, so `tc_core` transitively links gflags dynamically.

Tests link gflags directly.  I tried removing that on the CI machine, but it did not help.  Maybe some build artifact.

**Comment by nicolasvasilache** [comment]
Another option in a world where everyone is linking more and more things statically (pytorch 1.0 even links cuda libraries dynamically), is to ourselves go the static linking route as I had previously suggested. Are we more open to this now? @skimo-openhub ?

**Comment by ftynse** [comment]
Wasn't there a technical problem with static linking?

**Comment by skimo-openhub** [comment]
On Tue, Jul 03, 2018 at 11:57:56AM -0700, Nicolas Vasilache wrote:
> Another option in a world where everyone is linking more and more things statically (pytorch 1.0 even links cuda libraries dynamically), is to ourselves go the static linking route as I had previously suggested. Are we more open to this now? @skimo-openhub ?

I don't know why everyone is switching to static libraries.
I do think we shouldn't link in static libraries in a dynamic library.
I fixed the gflags issue in this PR.

skimo

**Comment by ftynse** [comment]
> I fixed the gflags issue in this PR.

Thanks!

**Comment by skimo-openhub** [comment]
On Wed, Jul 04, 2018 at 04:52:56AM -0700, skimo-openhub wrote:
> On Tue, Jul 03, 2018 at 11:57:56AM -0700, Nicolas Vasilache wrote:
> > Another option in a world where everyone is linking more and more things statically (pytorch 1.0 even links cuda libraries dynamically), is to ourselves go the static linking route as I had previously suggested. Are we more open to this now? @skimo-openhub ?
> 
> I don't know why everyone is switching to static libraries.
> I do think we shouldn't link in static libraries in a dynamic library.
> I fixed the gflags issue in this PR.

Actually, I made the error go away, but I'm not sure I fixed
the issue completely.
libgflags is still getting linked in several times,
because anything that depends on libtc_lang (including other
shared libraries) now links in libgflags.

skimo

**Pull request closed without merging**
