### PR TITLE
Improve autotuner UX (both C++ and python land)

### PR DESCRIPTION
**Pull request by nicolasvasilache**
This PR serves the purpose of running the autotuner more smoothly on a script sent by a user:

```
wget -P /tmphttps://gist.githubusercontent.com/nicolasvasilache/d069e701229cb07f4b03a4c7980ab737/raw/1eef01140cae9a1bac1e3d771bb9008827e752be/batch_renormalization.py
python setup.py install --prefix=/tmp
python /tmp/batch_renormalization.py
```

I have been hitting Ctrl + C when perf looked "reasonable", user experience feels pretty good to me and we seem able to recover from existing protos.

```
Copying tensor_comprehensions.egg-info to /tmp/lib/python3.6/site-packages/tensor_comprehensions-0.1.1-py3.6.egg-info
running install_scripts
[INFO]: Autotuning cache will be saved to: /tmp/calc_mean_std_2_256_32_32_6.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 44/661/1335
[INFO]: Tuned kernel options found, using those options
[INFO]: Autotuning cache will be saved to: /tmp/calc_r_d_256_256_256_256_6.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 8/9/34
[INFO]: Tuned kernel options found, using those options
[INFO]: Autotuning cache will be saved to: /tmp/calc_O_2_256_32_32_256_256_256_256_256_256.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 20/83/3784
[INFO]: Tuned kernel options found, using those options
[INFO]: Autotuning cache will be saved to: /tmp/calc_running_mean_std_256_256_256_256_6.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 8/9/37
[INFO]: Tuned kernel options found, using those options
[INFO]: Autotuning cache will be saved to: /tmp/calc_xHat_grad_256_2_256_32_32.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 11/31/65
[INFO]: Tuned kernel options found, using those options
[INFO]: Autotuning cache will be saved to: /tmp/calc_mean_std_grad_2_256_32_32_256_256_256_2_256_32_32.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 69/281/1745
Iteration 1     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 65/183/316
[INFO]: Tuned kernel options found, using those options
[INFO]: Autotuning cache will be saved to: /tmp/calc_xHat_2_256_32_32_256_256_256_256.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 12/57/70
[INFO]: Tuned kernel options found, using those options
[INFO]: Autotuning cache will be saved to: /tmp/calc_weight_bias_grad_2_256_32_32_2_256_32_32.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 70/220/2303
[INFO]: Tuned kernel options found, using those options
[INFO]: Autotuning cache will be saved to: /tmp/calc_I_grad_2_256_32_32_256_256_256_2_256_32_32_256_256.options
Iteration 0     Jobs(Compiled, Evaluated)/total  (100, 100)/100   (best/median/worst)us: 16/60/276
[INFO]: Tuned kernel options found, using those options
```

In the process, I had to debug a parameters issue in the second kernel. 
To print things properly it was also necessary to add operator<< to CpuMappingOptions.

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
cc @SSS135 who posted about this [here](https://gist.github.com/SSS135/d218f81dad12a0e5bab7665c1b5777ec)

**Comment by ftynse** [comment]
The changes to `operator<<` don't seem to belong into "fix Ctrl+C", but ok.

**Comment by ftynse** [comment]
> we seem able to recover from existing protos.

I find this behavior confusing as explained in #473.  In the worst case, dump those protos into the working directory, not `/tmp` to at least make them visible to the user.  If the tuning does not terminate the process on SIGINT, it can just as well return the best option found so far to make it usable from the code without some under-the-carpet communication through some temporary files.

**Comment by nicolasvasilache** [comment]
> I also wouldn't call it useless. It does terminate the tuning, but indeed takes time. 

The current flow is to send SIGINT, wait for some (lenghty) amount fo time, then crash because of the double join rendering the termination utterly useless. Arguable we could separate the double join from the rest but I'd call that splitting hairs. This PR makes it actually usable 

> An alternative solution I have been proposing was to run the entire tuning as a separate process. 

Sure, we've been kicking this around for months. If you have the cycles go for it, this is not the intent of this PR. When we implement your suggestion, let's be sure the API is simple enough that we can implement it as an external service too if needed.

**Comment by nicolasvasilache** [comment]
> The changes to operator<< don't seem to belong into "fix Ctrl+C", but ok.

I don't think we have strict rules wrt what can be included in a PR. This came up as part of investigating batch renormalization, the commits are well separated so that should satisfy our guidelines.

**Comment by nicolasvasilache** [comment]
> I find this behavior confusing

This is happening when implicitly loading a proto during tuning if a filename is passed. I'll send a followup PR that can either `tune` (from scratch) or `tuneFromCheckpoint` (or something similar). Not in this PR since this is the current intended behavior.

**Comment by ftynse** [comment]
> I don't think we have strict rules wrt what can be included in a PR. This came up as part of investigating batch renormalization, the commits are well separated so that should satisfy our guidelines.

Then let's turn this into policy.  I had to change my PRs repeatedly because of it.

**Pull request merged**
