### PR TITLE
Try small size for 2LUT test cases

### PR DESCRIPTION
**Pull request by prigoyal**
I am also sending this PR and can use this first in Jenkins CI. if it still fails, I can try to apply my other patch. :)

### CODE REVIEW

**Comment by prigoyal** [comment]
@nicolasvasilache can you help me get unblocked with either this PR or https://github.com/facebookresearch/TensorComprehensions/pull/151 

Thanks :)

**Comment by prigoyal** [comment]
tagging folks in PST/EST
@zdevito , @abadams do you feel comfortable with unblocking this PR or #151 ? :) thanks so much in advance for your help.

**Comment by abadams** [comment]
It's silly to require <10min turnaround times on your PRs for this stuff. Can't we just turn off requiring reviews until CI is up and working?

**Comment by prigoyal** [comment]
I am fine with that @abadams if everyone else is okay too. 

PyTorch, Caffe2, ONNX etc projects iterate quite fast on this with sending PRs and rolling Jenkins build.

**Comment by prigoyal** [comment]
trying out this solution first.

**Comment by ftynse** [comment]
> It's silly to require <10min turnaround times on your PRs for this stuff. Can't we just turn off requiring reviews until CI is up and working?

I suggested in another PR that CI can be set up on a separate branch fully, then reviewed as a single merge to master...

**Comment by prigoyal** [comment]
>> I suggested in another PR that CI can be set up on a separate branch fully, then reviewed as a single merge to master...

**Comment by prigoyal** [comment]
setting up branch doesn't really work because CI needs to be tested for PR incoming and also master. that will require sending all PR including users to that branch which is probably not a good idea :)

**Comment by ftynse** [comment]
I meant having a branch until CI is fully operational. Then switch it.  
For the purpose of testing, you can create PR targeted at a branch other 
than master (we already do that for dev).

**Comment by prigoyal** [comment]
thanks @ftynse for the PR, we set triggers based on users, admins etc and I would like to test those triggers other CI is not going to be be functional :) I am also learning Jenkins myself and trying to reduce any cognitive overhead and more work involved with switching branches in CI scripts, testing workflows etc.

removing the requirement of stamp seems the easiest way to go IMO but maybe not everyone will agree.

**Comment by ftynse** [comment]
well, if you update installation from source to **not** use master, you can commit whatever there

**Comment by prigoyal** [comment]
cc @hmansell

**Pull request merged**
